// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2ubpRBABr__WfmxnPTeGB3KyG1f9jJdg',
    appId: '1:105435914269:web:d2f27ded2b4dbab47466f4',
    messagingSenderId: '105435914269',
    projectId: 'dokuzn-d20f2',
    authDomain: 'dokuzn-d20f2.firebaseapp.com',
    storageBucket: 'dokuzn-d20f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAld2AJL1zmRVROl2SrdbO9H3XyMtkomxE',
    appId: '1:105435914269:android:61dbbd385709a71b7466f4',
    messagingSenderId: '105435914269',
    projectId: 'dokuzn-d20f2',
    storageBucket: 'dokuzn-d20f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbUOq8F3Qi-U2nlfgPd5vK4hNn6BYi6wg',
    appId: '1:105435914269:ios:c22443ee343f29a37466f4',
    messagingSenderId: '105435914269',
    projectId: 'dokuzn-d20f2',
    storageBucket: 'dokuzn-d20f2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbUOq8F3Qi-U2nlfgPd5vK4hNn6BYi6wg',
    appId: '1:105435914269:ios:c50589a38f0a6ef97466f4',
    messagingSenderId: '105435914269',
    projectId: 'dokuzn-d20f2',
    storageBucket: 'dokuzn-d20f2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
